"""
Sensitivity Engine Interface

Architecture v2.3 (Frozen MVP)

Defines the contract for feature sensitivity analysis.

The Sensitivity Engine explains WHY the churn model
produced its prediction.

Typical implementations may use:

    • SHAP
    • Permutation Importance
    • Feature Importance
    • Partial Dependence
    • Elasticity Analysis

The remainder of the system depends only on this
interface.
"""

from __future__ import annotations

from abc import ABC
from abc import abstractmethod

from mobile_ai_system.application.models.information_result import (
    InformationResult,
)
from mobile_ai_system.impact.models.churn_result import (
    ChurnResult,
)
from mobile_ai_system.impact.models.sensitivity_result import (
    SensitivityResult,
)


class ISensitivityEngine(ABC):
    """
    Interface for feature sensitivity analysis.

    This engine explains which features contributed
    most to predicted customer churn.

    It performs explanation rather than prediction.
    """

    @property
    @abstractmethod
    def engine_name(self) -> str:
        """
        Name of the explanation engine.

        Examples

            "shap"

            "permutation"

            "feature_importance"
        """
        ...

    @abstractmethod
    def analyze(
        self,
        information: InformationResult,
        churn: ChurnResult,
    ) -> SensitivityResult:
        """
        Analyze feature sensitivity.

        Parameters
        ----------
        information
            Structured business events retrieved by the
            Information Layer.

        churn
            Prediction generated by the Churn Engine.

        Returns
        -------
        SensitivityResult
        """
        ...

    @abstractmethod
    def supports_shap(self) -> bool:
        """
        Returns True if SHAP values are available.
        """
        ...

    @abstractmethod
    def supports_global_importance(self) -> bool:
        """
        Returns True if global feature importance
        analysis is supported.
        """
        ...